version: '3.7'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.7
    environment:
      - discovery.type=single-node
    deploy:
      placement:
        constraints: 
          - node.role == manager
    volumes:
      - type: volume
        source: esdata
        target: /usr/share/elasticsearch/data
    
    ports: 
      - target: 9200
        published: 9200
        protocol: tcp
        mode: host

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.7
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    deploy:
      placement:
        constraints: 
          - node.role == manager
    ports:
      - target: 5601
        published: 5601
        protocol: tcp
        mode: host

  web_nginx:
    image: nginx:latest
    deploy:
      replicas: 50
      placement:
        constraints: 
          - node.hostname == worker2
    ports:
      - target: 80
        published: 8080
        protocol: tcp
        mode: ingress

  metricbeat:
    image: docker.elastic.co/beats/metricbeat:7.17.7
    deploy:
      placement:
        constraints: 
          - node.hostname == worker2
    volumes:
      - type: bind
        source: /proc
        target: /hostfs/proc
        read_only: true
      - type: bind
        source: /sys/fs/cgroup
        target: /hostfs/sys/fs/cgroup
        read_only: true
      - type: bind
        source: /
        target: /hostfs
        read_only: true
    environment:
      - ELASTICSEARCH_HOSTS=elasticsearch:9200
      - KIBANA_HOST=kibana:5601
      - ELASTICSEARCH_USERNAME=comet
      - ELASTICSEARCH_PASSWORD=test123
    command: setup --dashboards -E setup.kibana.host=kibana:5601 -E output.elasticsearch.hosts=["elasticsearch:9200"]

volumes:
  esdata:

